### ISSUE TITLE
Investigate if magnetometer calibration is necessary after thruster swaps

### ISSUE THREAD

**Issue by duggerdufl** [uf-mil/SubjuGator#196]
Are the manufacturing differences in each new thruster enough to affect the magnetometer calibration?

**Comment by sentree** [comment]
Were the new thrusters in use at the last pool day? The sub was very stable near the end.

**Comment by duggerdufl** [comment]
Through testing it does not look like anything is being severely affected. There might be some small changes that we can not see through observation.

Here is some notes on it from uf-mil-archive: https://github.com/uf-mil-archive/getting-started/blob/master/magnetic-calibration.md

@forrestv Can you comment on this (you wrote that document)?

**Comment by sentree** [comment]
Looking at the text, it appears that it is able to also account for the metal in the sub. Perhaps we should wait until the new chassis is built and assembled to do a full calibration.

**Comment by duggerdufl** [comment]
Looks like only hardsoft calibrations are being applied, per https://github.com/uf-mil/Sub8/blob/master/command/sub8_launch/launch/subsystems/nav_box.launch

**Comment by mattlangford** [comment]
According to that launch it looks like the dynamic is being applied as well
from imu -- `/imu/mag_raw` --> [dynamic compensation] -- `/imu/mag_lessraw` --> [hardsoft compensation] -- `/imu/mag` --> UKF

**Comment by duggerdufl** [comment]
You're correct - I don't have a good understanding of launch files, saw the remap and just assumed it did that without changing anything.

**Comment by forrestv** [comment]
The dynamic compensation may be running, but AFAIK it's not doing anything since the thruster drivers don't publish their magnetic field contributions like the Sub7 thruster drivers did. If nothing is being published on `/imu/mag_generated_info`, that would confirm this. Given that, it's safe to remove from the launch file (though you'd have to keep everything connected by changing the remaps).

So, dynamic compensation is a no-op.

The hard/soft calibration should still be done any time anything near the magnetometer changes and ideally whenever anything metal anywhere on the sub changes.

**Comment by mattlangford** [comment]
Awesome, thanks!
