### ISSUE TITLE
Simulator is too dark

### ISSUE THREAD

**Issue by kev-the-dev** [uf-mil/SubjuGator#288]
The lighting in gazebo is really dark, which makes it difficult to use for perception testing. For navigator, we had the sim very bright, which allowed us to test in ideal conditions. We should move the light, add new ones, or make the lights brighter so everything is easily visible

**Comment by kev-the-dev** [comment]
For example, this is an actual screenshot from the simulated down camera:
![screenshot from 2017-06-24 12-28-31](https://user-images.githubusercontent.com/9502636/27510133-abdcc27c-58d8-11e7-8dc3-2ab3be3785b1.png)

**Comment by Grymessa** [comment]
I added a couple of light points and noticed its still pretty dark in some shots. Looking at it, there are spots that are exceedingly dark in the transdeck texture. It might be worth swapping out textures for something lighter. This is a screenshot of the ellipse table as seen from the down camera. By the bins, I still get a black screen essentially as with yours.
![screenshot from 2017-06-26 10-01-51](https://user-images.githubusercontent.com/5448610/27542890-9596f3f0-5a56-11e7-9b06-9c66fd04fc04.png)

**Comment by sentree** [comment]
Don't know if this has been fixed yet, but have a look at my lighting configuration from the NaviGator simulator. Specifically the [world file](https://github.com/uf-mil/NaviGator/blob/master/simulation/navigator_gazebo/worlds/a_whole_new.world). Basically, I just created 6 directional lights. Since most of the competition elements were vertical or horizontal planes, this added a lot of light to the simulator.
