### ISSUE TITLE
Add area search to channel marker mission segments

### ISSUE THREAD

**Issue by jpanikulam** [uf-mil/SubjuGator#98]
- Have some knowledge of where we should look and where we have already looked
- Visualize it in Rviz

**Comment by mattlangford** [comment]
Can this be closed or should we wait until it has been tested irl

**Comment by jpanikulam** [comment]
I am sufficiently satisfied that this is solved

**Comment by jpanikulam** [comment]
What'll be your strategy for making sure the search pattern doesn't hit the pool walls?

**Comment by mattlangford** [comment]
So the sub won't search outside the occupancy grid and since we know approximately where we start in the transdec (right?) we can define the grid such that the sub won't hit the walls.
Also for testing in pools we can define the grid to be approx the size of the pool based on where we put the sub in the water.

**Comment by jpanikulam** [comment]
Ok.

One of these days I'd like to have a single place (maybe a launch arg or param) that configures the sub to load calibrations for one of [gazebo, transdec, Town Parc pool]

Then, most importantly, lets the operator align a model of the pool in RVIZ.

**Comment by mattlangford** [comment]
Yeah that sounds like a good idea. 
Doing the pool alignment could be tricky, what were you thinking for that? If we made 3D model of the pool, positioning it would be tricky since we still wouldn't know where the sub was in the pool initially. Would that just be an approximate representation of the pool, if so what would that do for us besides being a starting point for the marker occupancy grid?
